### ISSUE TITLE
无法显示难度列表

### ISSUE THREAD

**Issue by Ghosin** [111116/osu#3]
* map: https://osu.ppy.sh/beatmapsets/814850
* version: v1.3.7.
* console: 
```
addbeatmaplist.js:77 
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at createDifficultyList (http://osugame.online/scripts/addbeatmaplist.js:77:24)
    at HTMLDivElement.box.onclick (http://osugame.online/scripts/addbeatmaplist.js:355:13)
```
* screenshot:
![](https://i.loli.net/2020/02/14/1ZCFjbwmWG8NBnx.png)

**Comment by 111116** [comment]
不过这个anti-PP图是什么原理啊（
